# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\gis_interface\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(140, 176, 151, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(30, 76, 100, 30))
        self.pushButton_search.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_search.setObjectName("pushButton_search")
        self.listWidget_city = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_city.setGeometry(QtCore.QRect(30, 110, 321, 291))
        self.listWidget_city.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget_city.setObjectName("listWidget_city")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 40, 321, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(460, 410, 321, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(460, 450, 200, 30))
        self.result_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.result_label.setObjectName('result_label')
        self.tableWidget_city_objects = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_city_objects.setGeometry(QtCore.QRect(460, 110, 321, 291))
        self.tableWidget_city_objects.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_city_objects.setObjectName("tableWidget_city_objects")
        self.tableWidget_city_objects.setColumnCount(0)
        self.tableWidget_city_objects.setRowCount(0)
        self.pushButton_check_city = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check_city.setGeometry(QtCore.QRect(140, 410, 100, 30))
        self.pushButton_check_city.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_check_city.setObjectName("pushButton_check_city")
        self.pushButton_openmap = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openmap.setEnabled(True)
        self.pushButton_openmap.setGeometry(QtCore.QRect(30, 410, 100, 30))
        self.pushButton_openmap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_openmap.setObjectName("pushButton_openmap")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_search.setText(_translate("MainWindow", "Іздеу"))
        self.pushButton_check_city.setText(_translate("MainWindow", "Бағалау"))
        self.pushButton_openmap.setText(_translate("MainWindow", "Картаны ашу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
